filetype off
call pathogen#runtime_append_all_bundles()

set nocompatible        " This must be first, because it changes other options as a side effect.

source $VIMRUNTIME/mswin.vim

let mapleader = ","

" Random Behavior
if has("vms")
  set nobackup          " do not keep a backup file, use versions instead
else
  set backup            " keep a backup file
endif
set history=50          " keep 50 lines of command line history
set showcmd             " display incomplete commands
set backspace=indent,eol,start " allow backspacing over everything in insert mode
set modelines=0         " no need for modelines, risky anyway
set scrolloff=3         " Scroll three lines before hitting the edge of the screen
set wildmenu            " show tab completion for commands above command line
set hidden              " keep buffers around if replaced via :e
set wildmode=list:full  " complete first match, and show list of matches
set visualbell          " Don't beep, just flash the screen quickly
set laststatus=2        " Always show status line for last window
set undofile            " keep persistent undo files

" Search behavior
set incsearch           " move the cursor as you type the search
set ignorecase          " by default, when searching
set smartcase           " override ignorecase if uppercase characters are typed
set gdefault            " replace all matches on a line by default
set showmatch           " Jump to matching bracket while searching
if &t_Co > 2 || has("gui_running")
  set hlsearch          " Also switch on highlighting the last used search pattern.
endif

" Appearance
set ruler               " show the cursor position all the time
set showmode            " display non-command modes in command line
set cursorline          " Highlight the line the cursor is on
set ttyfast             " Do faster updating of the screen
set relativenumber      " Do relative line numbering, rather than absolute
set list
set listchars=tab:>-,trail:-

" Tab stuff
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set smarttab

" Gui options
let &guioptions = substitute(&guioptions, "t", "", "g") " No tearoff menus
let &guioptions = substitute(&guioptions, "T", "", "g") " No toolbar
let &guioptions = substitute(&guioptions, "m", "", "g") " No menubar
let &guioptions = substitute(&guioptions, "r", "", "g") " No right scrollbar
let &guioptions = substitute(&guioptions, "L", "", "g") " No left scrollbar

" Don't use Ex mode, use Q for formatting
map Q gq

" CTRL-U in insert mode deletes a lot.  Use CTRL-G u to first break undo,
" so that you can undo CTRL-U after inserting a line break.
inoremap <C-U> <C-G>u<C-U>

" In many terminal emulators the mouse works just fine, thus enable it.
if has('mouse')
  set mouse=a
endif

" Switch syntax highlighting on, when the terminal has colors
" Also switch on highlighting the last used search pattern.
if &t_Co > 2 || has("gui_running")
  syntax on
  set hlsearch
endif

" Only do this part when compiled with support for autocommands.
if has("autocmd")

  " Enable file type detection.
  " Use the default filetype settings, so that mail gets 'tw' set to 72,
  " 'cindent' is on in C files, etc.
  " Also load indent files, to automatically do language-dependent indenting.
  filetype plugin indent on

  " Put these in an autocmd group, so that we can delete them easily.
  augroup vimrcEx
  au!

  " Save all files when losing focus
  autocmd FocusLost * :wa

  " For all text files set 'textwidth' to 78 characters.
  autocmd FileType text setlocal textwidth=78

  " Show the cursor line for the current window only
  autocmd WinEnter * setlocal cursorline
  autocmd WinLeave * setlocal nocursorline

  " Start gvim maximized
  autocmd GUIEnter * simalt ~x

  " When editing a file, always jump to the last known cursor position.
  " Don't do it when the position is invalid or when inside an event handler
  " (happens when dropping a file on gvim).
  " Also don't do it when the mark is in the first line, that is the default
  " position when opening a file.
  autocmd BufReadPost *
    \ if line("'\"") > 1 && line("'\"") <= line("$") |
    \   exe "normal! g`\"" |
    \ endif

  augroup END

else
  set autoindent		" always set autoindenting on
endif " has("autocmd")

" Convenient command to see the difference between the current buffer and the
" file it was loaded from, thus the changes you made.
" Only define it when not defined already.
if !exists(":DiffOrig")
  command DiffOrig vert new | set bt=nofile | r # | 0d_ | diffthis
		  \ | wincmd p | diffthis
endif

" Tab and windows movement
:nn <C-Tab> <C-PageDown>
:nn <C-S-Tab> <C-PageUp>
:nn <C-PageDown> <C-W>w
:nn <C-PageUp> <C-W>W
:vn <C-Tab> <C-PageDown>
:vn <C-S-Tab> <C-PageUp>
:vn <C-PageDown> <C-W>w
:vn <C-PageUp> <C-W>W
:ino <C-Tab> <C-PageDown>
:ino <C-S-Tab> <C-PageUp>
:ino <C-PageDown> <C-W>w
:ino <C-PageUp> <C-W>W

" Disable arrow keys
nnoremap <up> <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>
inoremap <up> <nop>
inoremap <down> <nop>
inoremap <left> <nop>
inoremap <right> <nop>

" Use tab to switch between block delimiters
nnoremap <tab> %
vnoremap <tab> %

" Make j/k go up/down by screen lines, not file lines
nnoremap j gj
nnoremap k gk

" Make it easier to enter command mode
nnoremap ; :

" easily clear current search
nnoremap <leader><space> :noh<cr>

" Use the arrow keys for switching buffers
noremap <right> :bnext<cr>
noremap <left> :bprev<cr>

" Insert date/time stamps
nmap <F3> Go<C-R>=strftime("[%Y-%m-%d %a %I:%M %p]\n")<CR>
imap <F3> <ESC>Go<C-R>=strftime("[%Y-%m-%d %a %I:%M %p]\n")<CR>

" Store backup, swap, and undo files
set directory=~/vimfiles/temp/,c:/tmp,c:/temp
set backupdir=~/vimfiles/temp/,c:/tmp,c:/temp
set undodir=~/vimfiles/undo
